name: Generate README every 1 hour

on: 
  schedule:
     - cron: "0 * * * *"
  workflow_dispatch:

jobs:
   stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Let the magic happen
        uses: actions/setup-node@v1
        with:
          node-version: 12.15.0

      - run: npm i
      - run: node .   
        
            

      - name: Add to git repo
        run: |
           git add .
           git commit -m "[Magic] Automated Readme update"
        
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
