name: Waka Readme

on:
  workflow_dispatch:
  schedule:
   - cron: "30 18 * * *"

jobs:
  update-readme:
    name: Update Readme with Wakatime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "Flase"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "Flase"
          SHOW_OS: "Flase"
          SHOW_EDITORS: "Flase"
          SHOW_TOTAL_CODE_TIME: "Flase"
